apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pac-twxw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pac-twxw
    app.kubernetes.io/part-of: build-suite-test-application-zcph
  name: test-component-pac-twxw
  namespace: build-e2e-pbus-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-pac-twxw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-pac-twxw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:de5e869a68c7f47870eb1397061943e7f828ac7eb457d2998dfc41bcdb6c94bf
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
